site_name: Gumpo
site_url: https://example.com/
nav:
  - Home: index.md
  - Intro: intro.md
  - About: about.md
  - Background: background.md
  - New Engine: new_engine.md
  - Storage: storage.md
  - Energy Cost: energy_cost.md
  - Resources: resources.md
  - References: references.md
  - About Me: about_me.md

theme: readthedocs
